### ISSUE TITLE
运行报错问题

### ISSUE THREAD

**Issue by Lichen0113** [nie-lang/UDIS2#11]
你好作者，我在运行test.py的时候将地址改为了数据集所在的绝对地址或相对地址：
`parser.add_argument('--test_path', type=str, default="E:\\stitchingCode\\UDIS-D\\testing\\")`
或`parser.add_argument('--test_path', type=str, default="../../../UDIS-D/testing/")`
但是在运行时都报了**KeyError: 'input1'**错误
具体的输出如下：
`<==================== Loading data ===================>`
`Namespace(batch_size=1, gpu='0', test_path='E:\\stitchingCode\\UDIS-D\\testing\\')`
`odict_keys([])`
`load model from E:\stitchingCode\UDIS2\Warp\model\epoch100_model.pth!`
`##################start testing#######################`
`Traceback (most recent call last):`
`  File "E:/stitchingCode/UDIS2/Warp/Codes/test.py", line 124, in <module>`
`    test(args)`
`  File "E:/stitchingCode/UDIS2/Warp/Codes/test.py", line 57, in test`
`    for i, batch_value in enumerate(test_loader):`
`  File "E:\Anaconda3\envs\nl\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__`
`    return self._get_iterator()`
`  File "E:\Anaconda3\envs\nl\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator`
`    return _MultiProcessingDataLoaderIter(self)`
`  File "E:\Anaconda3\envs\nl\lib\site-packages\torch\utils\data\dataloader.py", line 827, in __init__`
`    self._reset(loader, first_iter=True)`
`  File "E:\Anaconda3\envs\nl\lib\site-packages\torch\utils\data\dataloader.py", line 857, in _reset`
`    self._try_put_index()`
`  File "E:\Anaconda3\envs\nl\lib\site-packages\torch\utils\data\dataloader.py", line 1091, in _try_put_index`
`    index = self._next_index()`
`  File "E:\Anaconda3\envs\nl\lib\site-packages\torch\utils\data\dataloader.py", line 427, in _next_index`
`    return next(self._sampler_iter)  # may raise StopIteration`
`  File "E:\Anaconda3\envs\nl\lib\site-packages\torch\utils\data\sampler.py", line 227, in __iter__`
`    for idx in self.sampler:`
`  File "E:\Anaconda3\envs\nl\lib\site-packages\torch\utils\data\sampler.py", line 67, in __iter__`
`    return iter(range(len(self.data_source)))`
`  File "E:\stitchingCode\UDIS2\Warp\Codes\dataset.py", line 102, in __len__`
`    return len(self.datas['input1']['image'])`
`KeyError: 'input1'`
看上去像是没有读取到正确路径，想请教一下如何解决，万分感谢！

**Comment by nie-lang** [comment]
请注意数据集文件夹目录形式应该是
UDIS-D
**training
****input1
****input2
**testing
****input1
****input2

从你的输出结果来看，在你指定的testing目录下没有找到input1/input2文件夹。请检查是缺少文件还是路径格式错误。建议debug时输出下实际读取的路径和读取的文件名，以方便检查

**Comment by Lichen0113** [comment]
感谢大佬解答，问题已解决~

**Comment by BlackFisak** [comment]
> 感谢大佬解答，问题已解决~

您好，我在train.py文件中遇到了同样的问题，怎么修改路径都是报错，且与您的报错信息一致。请问您是如何修改的？

**Comment by JTDeve** [comment]
如何解决也不说一下吗

**Comment by ZhangHe-sys** [comment]
> > 感谢大佬解答，问题已解决~
> 
> 您好，我在train.py文件中遇到了同样的问题，怎么修改路径都是报错，且与您的报错信息一致。请问您是如何修改的？

您好，请问您遇到的问题最后解决了吗
