### ISSUE TITLE
warp测试其他数据集

### ISSUE THREAD

**Issue by Bethexone** [nie-lang/UDIS2#22]
`Test on other datasets
When testing on other datasets with different scenes and resolutions, we apply the iterative warp adaption to get better alignment performance.

Set the 'path/img1_name/img2_name' in Warp/Codes/**test_output.py.** (By default, both img1 and img2 are placed under 'path')

python **test_other.py**
The results before/after adaption will be generated and saved at 'path'.
`
以上是我对readme的引用，上文提及了两个文件，请问是修改test_output还是应该修改test_other文件？

**Comment by nie-lang** [comment]
多谢提醒，已经更正了。只需修改 test_other.py 文件即可
