### ISSUE TITLE
Question about Global Transformation in Warping

### ISSUE THREAD

**Issue by kjy09** [nie-lang/UDIS2#28]
Thank you for the great work. Since I am a beginner in this field, I have a question about the global transformation as follows:
![1717073755063](https://github.com/nie-lang/UDIS2/assets/22428544/addae7c1-78a2-467b-8d97-e96d9fa2d742)
Why use H_mat to warp the target feature instead of H?

**Comment by nie-lang** [comment]
Compared with H, H_mat normalized the pixel coordinates from [0, W]*[0, H] to [-1, 1]*[-1, 1]. It can be better adapted to other resolutions in the warping function.

**Comment by kjy09** [comment]
> Compared with H, H_mat normalized the pixel coordinates from [0, W]x[0, H] to [-1, 1]x[-1, 1]. It can be better adapted to other resolutions in the warping function.

I see. Many thanks for your reply.

**Comment by kjy09** [comment]
I see. Many thanks for your reply.
