### ISSUE TITLE
您上传在Google Drive的UDIS数据集似乎有问题，与百度网盘的数据不一致，训练集的Input1与Input2的数量不一致。

### ISSUE THREAD

**Issue by herepost** [nie-lang/UDIS2#30]
Google Drive中训练集的Input1与Input2的数量分别为10440张与10458张，这会导致训练时加载数据发生越界。而百度网盘中的两个压缩包则不存在这样的问题，数量均为10440张。目前尚不清楚是不是Google Drive的Bug导致，但是建议以压缩包形式上传。

**Comment by nie-lang** [comment]
感谢提醒，已更新Google Drive.
