### ISSUE TITLE
OOM when run test_output.py during Warp.

### ISSUE THREAD

**Issue by LorenzoSun-V** [nie-lang/UDIS2#32]
在Warp的代码中，训练完的模型运行test_output.py会遇到显存溢出的问题，且溢出很多：
![image](https://github.com/user-attachments/assets/15e2a12d-b155-47c9-b4ce-6be179bcab3a)

**Comment by xianghong2023** [comment]
我也遇到了这个问题，请问你解决了吗？

**Comment by LorenzoSun-V** [comment]
@xianghong2023 你好，还没有解决。

**Comment by cyzf1007hh** [comment]
减小batchsize，或者在每一次train（arg）后面加上torch.cuda.empty_cache()

**Comment by Farenweh** [comment]
我遇到了类似的问题，请检查一下你的testing/input1下面有没有000001.jpg，我从谷歌网盘下载的数据集出现此问题，导致图片配对出现错误，意外创造了巨大的张量画布。修正此错误后就ok了

**Comment by LorenzoSun-V** [comment]
@Farenweh 感谢
