### ISSUE TITLE
复现结果

### ISSUE THREAD

**Issue by jia199903** [nie-lang/UDIS2#6]
您好，请问一下训练的时候还需要自己调参吗？有用到随机种子吗？我在复现的时候总是达不到论文中的指标

**Comment by nie-lang** [comment]
好像没有随机种子之类的。检查下mesh分辨率，epoch数量，resnet50预训练模型是否启用，batch szie数量这些细节。如果这些都没问题的话，可能是与具体的环境有关，如GPU、CUDA、torch版本等

**Comment by jia199903** [comment]
好的，感谢~
