### ISSUE TITLE
图像大小

### ISSUE THREAD

**Issue by jia199903** [nie-lang/UDIS2#9]
请问一下，如果训练自己的数据集，可以通过修改代码训练任意尺寸的图片吗，这有可能实现吗

**Comment by nie-lang** [comment]
在dataloader中会自动修改图像分辨率为512*512。想要训练自己的其他分辨率数据集的话，1）可以就直接在512*512的分辨率下直接train，2）也可以修改网络结构来适合这个分辨率。

**Comment by jia199903** [comment]
请问如果修改网络结构的话
![image](https://github.com/nie-lang/UDIS2/assets/126779643/26ccce33-208b-4492-b81c-7d317fb39185)
这个地方的512是不是也应该修改，应该改成什么呢？
